services:
  db:
    image: mysql:8
    command: --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
    ports:
      - 3306:3306
  cache:
    image: memcached:alpine
    ports:
      - 11211:11211