version: '3'
services:
  db:
    image: mysql:8
    command: --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  cache:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  db-data: