name: Redis MySQL Test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  redis-mysql-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build packages
        run: npm run build --workspaces

      - name: Install dependencies in example
        run: npm install
        working-directory: ./examples/redis-mysql

      - name: Build example
        run: npm run build
        working-directory: ./examples/redis-mysql

      - name: Run Docker Compose and tests
        run: npm test
        working-directory: ./examples/redis-mysql
